stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  #TARGET_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  TARGET_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_BRANCH 

token-test:
  stage: test
  image: registry.gitlab.com/eflam/builder:main
  tags: ["flamingo", "google", "kubernetes" ]
  variables:
    SERUM_DEX_BPF_FILE_PATH: contrib/serum-dex/dex/target/deploy/serum_dex.so
    SERUM_DEX_WALLET: contrib/serum-dex/dex/target/deploy/serum_dex-keypair.json
  script:
    - ( cd contrib/serum-dex/dex && anchor build )
    - go test -timeout 30s -run ^TestMintToken$ github.com/gagliardetto/solana-go/programs/serum/client
